language: java

branches:
  only:
  - master

addons:
  sonarcloud:
    organization: "switcherapi"
    token: ${SONAR_TOKEN}

cache:
  directories:
  - $HOME/.m2
      
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=switcherapi_switcher-client